version: '3.6'
services:
  dokos-db:
    image: postgres
    #hostname: postgres
    container_name: dokos-database
    environment:
      POSTGRES_PASSWORD: SOkoD
      POSTGRES_USER: CheeseWillAlwaysLose
      POSTGRES_DB: dokos-db
    ports:
      #- 5433:5432
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433

  back:
    build:
      target:  finalApp
    image: dokos-backend
    container_name: dokos-backend
    #environment:
    #  WAIT_HOSTS: postgres:5433
    ports:
      - 8090:8080
    depends_on:
      - dokos-db
    networks:
      - backdb
    #  - frontback

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge