# version: '3.6'
services:
  dokosdb:
    image: postgres
    #hostname: postgres
    container_name: dokos-database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dokos-db
    ports:
      #- 5433:5432
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433

  back:
    build:
      target:  finalApp
    image: dokos-backend
    container_name: dokos-backend
    ports:
      - 8090:8080
    depends_on:
      - dokosdb
    networks:
      - backdb

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge